version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: fastApi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fastApiDatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql_network
    restart: always

volumes:
  mysql-data:
    driver: local

networks:
  mysql_network:
    driver: bridge
