version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: fastApi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fastApiDatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app_network
    restart: always
  
  mongodb:
    image: mongo:6.0
    container_name: fastApi-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app_network
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=fastApiMongoDB

volumes:
  mysql-data:
    driver: local
  mongodb-data:
    driver: local

networks:
  app_network:
    driver: bridge
